/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as InviteAcceptRouteImport } from './routes/invite/accept'
import { Route as AppRecordsIndexRouteImport } from './routes/_app/records/index'
import { Route as AppRecordsObjectApiNameIndexRouteImport } from './routes/_app/records/$objectApiName/index'
import { Route as AppRecordsObjectApiNameRecordIdRouteImport } from './routes/_app/records/$objectApiName/$recordId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecordsIndexRoute = AppRecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsObjectApiNameIndexRoute =
  AppRecordsObjectApiNameIndexRouteImport.update({
    id: '/records/$objectApiName/',
    path: '/records/$objectApiName/',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecordsObjectApiNameRecordIdRoute =
  AppRecordsObjectApiNameRecordIdRouteImport.update({
    id: '/records/$objectApiName/$recordId',
    path: '/records/$objectApiName/$recordId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/settings': typeof AppSettingsRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/records/': typeof AppRecordsIndexRoute
  '/records/$objectApiName/$recordId': typeof AppRecordsObjectApiNameRecordIdRoute
  '/records/$objectApiName/': typeof AppRecordsObjectApiNameIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/settings': typeof AppSettingsRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/': typeof AppIndexRoute
  '/records': typeof AppRecordsIndexRoute
  '/records/$objectApiName/$recordId': typeof AppRecordsObjectApiNameRecordIdRoute
  '/records/$objectApiName': typeof AppRecordsObjectApiNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/settings': typeof AppSettingsRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/_app/': typeof AppIndexRoute
  '/_app/records/': typeof AppRecordsIndexRoute
  '/_app/records/$objectApiName/$recordId': typeof AppRecordsObjectApiNameRecordIdRoute
  '/_app/records/$objectApiName/': typeof AppRecordsObjectApiNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/settings'
    | '/invite/accept'
    | '/records/'
    | '/records/$objectApiName/$recordId'
    | '/records/$objectApiName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/settings'
    | '/invite/accept'
    | '/'
    | '/records'
    | '/records/$objectApiName/$recordId'
    | '/records/$objectApiName'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/_app/settings'
    | '/invite/accept'
    | '/_app/'
    | '/_app/records/'
    | '/_app/records/$objectApiName/$recordId'
    | '/_app/records/$objectApiName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/records/': {
      id: '/_app/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof AppRecordsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records/$objectApiName/': {
      id: '/_app/records/$objectApiName/'
      path: '/records/$objectApiName'
      fullPath: '/records/$objectApiName/'
      preLoaderRoute: typeof AppRecordsObjectApiNameIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records/$objectApiName/$recordId': {
      id: '/_app/records/$objectApiName/$recordId'
      path: '/records/$objectApiName/$recordId'
      fullPath: '/records/$objectApiName/$recordId'
      preLoaderRoute: typeof AppRecordsObjectApiNameRecordIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRecordsIndexRoute: typeof AppRecordsIndexRoute
  AppRecordsObjectApiNameRecordIdRoute: typeof AppRecordsObjectApiNameRecordIdRoute
  AppRecordsObjectApiNameIndexRoute: typeof AppRecordsObjectApiNameIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppRecordsIndexRoute: AppRecordsIndexRoute,
  AppRecordsObjectApiNameRecordIdRoute: AppRecordsObjectApiNameRecordIdRoute,
  AppRecordsObjectApiNameIndexRoute: AppRecordsObjectApiNameIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  InviteAcceptRoute: InviteAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
